// 网关与服务器通讯协议

// protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative  gw.proto
// protoc --go_out=. --go_opt=paths=source_relative gw.proto
// protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. gw.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: gw.proto

package gw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// tos 发送给服务器
type StreamTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` //连接透传id  对长连接需要 对每一个链接都是唯一的
	Msg      uint32 `protobuf:"varint,2,opt,name=msg,proto3" json:"msg,omitempty"`                          // 消息编号
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                         // 数据
}

func (x *StreamTos) Reset() {
	*x = StreamTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTos) ProtoMessage() {}

func (x *StreamTos) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTos.ProtoReflect.Descriptor instead.
func (*StreamTos) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{0}
}

func (x *StreamTos) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamTos) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *StreamTos) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// tog 发送给网关
type StreamTog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` //连接透传id    对长连接需要 对每一个链接都是唯一的
	AllUid   bool     `protobuf:"varint,2,opt,name=all_uid,json=allUid,proto3" json:"all_uid,omitempty"`      //全服在线玩家广播
	Uids     []string `protobuf:"bytes,3,rep,name=uids,proto3" json:"uids,omitempty"`                         //广播给指定玩家
	Msg      uint32   `protobuf:"varint,4,opt,name=msg,proto3" json:"msg,omitempty"`                          //消息编号
	Data     []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                         //数据
}

func (x *StreamTog) Reset() {
	*x = StreamTog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamTog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTog) ProtoMessage() {}

func (x *StreamTog) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTog.ProtoReflect.Descriptor instead.
func (*StreamTog) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{1}
}

func (x *StreamTog) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamTog) GetAllUid() bool {
	if x != nil {
		return x.AllUid
	}
	return false
}

func (x *StreamTog) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *StreamTog) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *StreamTog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// tos 发送给服务器
type UnitaryTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  uint32 `protobuf:"varint,1,opt,name=msg,proto3" json:"msg,omitempty"`  //  消息编号
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` //     数据
}

func (x *UnitaryTos) Reset() {
	*x = UnitaryTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitaryTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitaryTos) ProtoMessage() {}

func (x *UnitaryTos) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitaryTos.ProtoReflect.Descriptor instead.
func (*UnitaryTos) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{2}
}

func (x *UnitaryTos) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *UnitaryTos) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// tog 发送给服务器
type UnitaryTog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  uint32 `protobuf:"varint,1,opt,name=msg,proto3" json:"msg,omitempty"`  //  消息编号
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` //     数据
}

func (x *UnitaryTog) Reset() {
	*x = UnitaryTog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitaryTog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitaryTog) ProtoMessage() {}

func (x *UnitaryTog) ProtoReflect() protoreflect.Message {
	mi := &file_gw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitaryTog.ProtoReflect.Descriptor instead.
func (*UnitaryTog) Descriptor() ([]byte, []int) {
	return file_gw_proto_rawDescGZIP(), []int{3}
}

func (x *UnitaryTog) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *UnitaryTog) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gw_proto protoreflect.FileDescriptor

var file_gw_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4f,
	0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x7c, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x6f, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6c,
	0x6c, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x6c, 0x6c,
	0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x33, 0x0a,
	0x0b, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x33, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x6f,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x76, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x36, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d,
	0x73, 0x67, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74,
	0x6f, 0x73, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74,
	0x6f, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x55, 0x6e, 0x69, 0x74, 0x61, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x73, 0x1a, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x67, 0x22, 0x00, 0x42,
	0x22, 0x5a, 0x20, 0x7a, 0x68, 0x75, 0x67, 0x65, 0x64, 0x61, 0x6f, 0x6a, 0x69, 0x61, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x67, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gw_proto_rawDescOnce sync.Once
	file_gw_proto_rawDescData = file_gw_proto_rawDesc
)

func file_gw_proto_rawDescGZIP() []byte {
	file_gw_proto_rawDescOnce.Do(func() {
		file_gw_proto_rawDescData = protoimpl.X.CompressGZIP(file_gw_proto_rawDescData)
	})
	return file_gw_proto_rawDescData
}

var file_gw_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gw_proto_goTypes = []interface{}{
	(*StreamTos)(nil),  // 0: pb.stream_tos
	(*StreamTog)(nil),  // 1: pb.stream_tog
	(*UnitaryTos)(nil), // 2: pb.unitary_tos
	(*UnitaryTog)(nil), // 3: pb.unitary_tog
}
var file_gw_proto_depIdxs = []int32{
	0, // 0: pb.Proxy.ProxyStreamMsg:input_type -> pb.stream_tos
	2, // 1: pb.Proxy.ProxyUnitaryMsg:input_type -> pb.unitary_tos
	1, // 2: pb.Proxy.ProxyStreamMsg:output_type -> pb.stream_tog
	3, // 3: pb.Proxy.ProxyUnitaryMsg:output_type -> pb.unitary_tog
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gw_proto_init() }
func file_gw_proto_init() {
	if File_gw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamTog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitaryTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitaryTog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gw_proto_goTypes,
		DependencyIndexes: file_gw_proto_depIdxs,
		MessageInfos:      file_gw_proto_msgTypes,
	}.Build()
	File_gw_proto = out.File
	file_gw_proto_rawDesc = nil
	file_gw_proto_goTypes = nil
	file_gw_proto_depIdxs = nil
}
