gfcli:
  gen:
    dao:
      - link:     "mysql:housekeeping_service:#wfFSsW#yHjfyqtkZ5xIFMTWkYQr7Qlu@tcp(127.0.0.1:3306)/housekeeping_service3"
        tables:   "sys_user,sys_user_account,sys_user_password,base_org,sys_user_org,sys_user"
        jsonCase: "CamelLower"

      #- link:   "mysql:housekeeping_service:#wfFSsW#yHjfyqtkZ5xIFMTWkYQr7Qlu@tcp(127.0.0.1:3306)/housekeeping_service3"
      #  path:   "./my-app"
      #  prefix: "primary_"
      #  tables: "user, userDetail"
#
  # sqlite需要自行编译带sqlite驱动的gf，下载库代码后修改路径文件（gf\cmd\gf\internal\cmd\cmd_gen_dao.go）的import包，取消注释即可。sqlite驱动依赖了gcc
  #- link: "sqlite:./file.db"